from . import res_country_extension
from . import res_country_state_extension
from . import logistics_saved_location
from . import logistics_direct_delivery_rule
from . import logistics_region
from . import logistics_fsa
from . import logistics_fsa_zone
from . import logistics_city
from . import logistics_region_destination
from . import logistics_equipment_profile
from . import fleet_vehicle
from . import logistics_lane
from . import logistics_service_level
from . import logistics_service_offering
from . import logistics_holiday_calendar
from . import logistics_lane_schedule
from . import logistics_rate_plan
from . import logistics_rate_tier
from . import logistics_fsa_rate_adjustment
from . import logistics_surcharge_type
from . import logistics_customer_rate
from . import logistics_pricing_session
from . import logistics_pricing_session_stop
from . import logistics_booking_line
from . import logistics_booking_stop
from . import logistics_booking_leg
from . import logistics_booking
from . import account_move_booking
from . import logistics_corridor
from . import dispatch_job_extension
from . import logistics_route_run
from . import logistics_route_template
from . import logistics_custom_quote
from . import logistics_recurring_agreement
from . import logistics_daily_local
from . import res_partner_logistics
from . import res_config_settings
from . import logistics_hub
