from . import dispatch_stage
from . import dispatch_stop
from . import dispatch_item
from . import dispatch_assignment_log
from . import dispatch_job
from . import fleet_vehicle
from . import dispatch_feasibility
from . import dispatch_adhoc_wizard
from . import dispatch_consolidation_wizard
from . import dispatch_chat_invite_wizard
from . import voip_call_extension
from . import account_move_dispatch
from . import sale_order_dispatch
from . import dispatch_consolidation
from . import dispatch_crossdock
from . import dispatch_timeline
from . import dispatch_location
from . import dispatch_detention
from . import res_partner_dispatch
from . import dispatch_reports
from . import dispatch_vehicle_layout
from . import dispatch_pallet_allocation
from . import dispatch_load_plan_event
from . import dispatch_document
from . import dispatch_load_plan
from . import dispatch_load_plan_optimizer
from . import dispatch_book_load_wizard
from . import dispatch_location_photo
from . import dispatch_location_extraction
from . import dispatch_route_visit
from . import dispatch_hours_override
from . import dispatch_route_adviser
from . import dispatch_proof_override
from . import dispatch_load_plan_operation
from . import dispatch_error_log
from . import dispatch_workday
from . import dispatch_evidence
from . import dispatch_popp_override
from . import driver_guided_flow
from . import driver_update
