from . import dispatch_stage
from . import dispatch_stop
from . import dispatch_item
from . import dispatch_assignment_log
from . import dispatch_job
from . import dispatch_feasibility
from . import dispatch_adhoc_wizard
from . import dispatch_duplicate_job_wizard
from . import dispatch_consolidation_wizard
from . import dispatch_chat_invite_wizard
from . import voip_call_extension
from . import account_move_dispatch
from . import sale_order_dispatch
from . import booking_template
from . import dispatch_consolidation
from . import dispatch_crossdock
from . import dispatch_timeline
from . import dispatch_location
from . import res_partner_dispatch
from . import dispatch_reports
from . import dispatch_vehicle_layout
from . import dispatch_pallet_allocation
from . import dispatch_load_plan_event
from . import dispatch_document
from . import dispatch_load_plan
